In [3]:
import numpy as np

# 1.1. Створити вектор, скаляр, матрицю та тензор
# Скаляр (0D тензор)
scalar = np.array(10.0, dtype=np.float32)

# Вектор (1D тензор)
vector = np.array([1, 2, 3, 4, 5], dtype=np.int32)

# Матриця (2D тензор)
matrix = np.array([[6., 7.],
                   [8., 9.]], dtype=np.float32)

# Тензор (3D тензор)
tensor_3d = np.array([[[1.1, 2.2],
                       [3.3, 4.4]],
                      [[5.5, 6.6],
                       [7.7, 8.8]]], dtype=np.float32)

print("Скаляр:\n", scalar)
print("\nВектор:\n", vector)
print("\nМатриця:\n", matrix)
print("\n3D Тензор:\n", tensor_3d)

Скаляр:
 10.0

Вектор:
 [1 2 3 4 5]

Матриця:
 [[6. 7.]
 [8. 9.]]

3D Тензор:
 [[[1.1 2.2]
  [3.3 4.4]]

 [[5.5 6.6]
  [7.7 8.8]]]


In [4]:
# 1.2. Знайти форму, ранг та розмір
print("\n--- Форма, Ранг, Розмір ---")
tensors = {"Скаляр": scalar, "Вектор": vector, "Матриця": matrix, "3D Тензор": tensor_3d}

for name, t in tensors.items():
    print(f"\n{name}:")
    print(f"  Форма (Shape): {t.shape}")
    print(f"  Ранг (Rank): {np.ndim(t)}")
    print(f"  Розмір (Size): {t.size}")


--- Форма, Ранг, Розмір ---

Скаляр:
  Форма (Shape): ()
  Ранг (Rank): 0
  Розмір (Size): 1

Вектор:
  Форма (Shape): (5,)
  Ранг (Rank): 1
  Розмір (Size): 5

Матриця:
  Форма (Shape): (2, 2)
  Ранг (Rank): 2
  Розмір (Size): 4

3D Тензор:
  Форма (Shape): (2, 2, 2)
  Ранг (Rank): 3
  Розмір (Size): 8


In [7]:
# 1.3. Створити два тензори випадкових значень між 0 та 1, форми [5, 300]
np.random.seed(42) # для відтворюваності

tensor_A = np.random.uniform(low=0.0, high=1.0, size=(5, 300))
tensor_B = np.random.uniform(low=0.0, high=1.0, size=(5, 300))

print("\n--- Випадкові Тензори [5, 300] ---")
print("Tensor A (перші 5 значень):\n", tensor_A[:, :5])
print("Tensor B (перші 5 значень):\n", tensor_B[:, :5])


--- Випадкові Тензори [5, 300] ---
Tensor A (перші 5 значень):
 [[0.37454012 0.95071431 0.73199394 0.59865848 0.15601864]
 [0.05168172 0.53135463 0.54063512 0.6374299  0.72609133]
 [0.16893506 0.27859034 0.17701048 0.08870253 0.12063587]
 [0.20788626 0.0265322  0.18143544 0.58304156 0.42142455]
 [0.7582632  0.02458692 0.02212355 0.32361022 0.48864319]]
Tensor B (перші 5 значень):
 [[0.51908179 0.47918188 0.02564207 0.34124783 0.38019562]
 [0.9565014  0.73750836 0.35325141 0.29653558 0.34970323]
 [0.91509007 0.53302887 0.15795482 0.69589912 0.79326135]
 [0.34060417 0.07171189 0.40962889 0.3112175  0.67712064]
 [0.52129605 0.97601382 0.12555021 0.01694766 0.77015821]]


In [8]:
# 1.4. Множення матриць (dot product).
# Щоб помножити [5, 300] на [5, 300], потрібно транспонувати Tensor_B, щоб отримати [5, 300] @ [300, 5]
tensor_B_transposed = tensor_B.T

matrix_multiplication_result = np.matmul(tensor_A, tensor_B_transposed)

print("\n--- Множення Матриць (np.matmul) ---")
print("Форма Tensor A:", tensor_A.shape)
print("Форма Tensor B транспонованого:", tensor_B_transposed.shape)
print("Форма Результату:", matrix_multiplication_result.shape)
print("Результат (перші 3x3):\n", matrix_multiplication_result[:3, :3])


--- Множення Матриць (np.matmul) ---
Форма Tensor A: (5, 300)
Форма Tensor B транспонованого: (300, 5)
Форма Результату: (5, 5)
Результат (перші 3x3):
 [[72.56983949 74.43868779 74.48605938]
 [76.21593412 76.40502288 75.1791935 ]
 [69.15425383 69.86131484 70.05061316]]


In [9]:
# 1.5. Скалярний добуток (поелементне множення - element-wise multiplication)
element_wise_multiplication_result = tensor_A * tensor_B
# Або: element_wise_multiplication_result = tf.multiply(tensor_A, tensor_B)

print("\n--- Скалярний Добуток (Element-wise) ---")
print("Форма Результату:", element_wise_multiplication_result.shape)
print("Результат (перші 2x5):\n", element_wise_multiplication_result[:2, :5])


--- Скалярний Добуток (Element-wise) ---
Форма Результату: (5, 300)
Результат (перші 2x5):
 [[0.19441695 0.45556507 0.01876984 0.20429091 0.0593176 ]
 [0.04943364 0.39187848 0.19098012 0.18902065 0.25391648]]


In [10]:
# 1.6. Створити тензор випадкових значень форми [1, 224, 224, 3]
np.random.seed(42)
image_tensor = np.random.uniform(low=0.0, high=255.0, size=(1, 224, 224, 3)).astype(np.float32)

print("\n--- Image Tensor [1, 224, 224, 3] ---")
print("Форма:", image_tensor.shape)
print("Мінімальне значення (приблизно):", np.min(image_tensor))
print("Максимальне значення (приблизно):", np.max(image_tensor))


--- Image Tensor [1, 224, 224, 3] ---
Форма: (1, 224, 224, 3)
Мінімальне значення (приблизно): 0.0014118523
Максимальне значення (приблизно): 254.99797


In [11]:
# 1.7. Знайти мінімальне та максимальне значення
min_value = np.min(image_tensor)
max_value = np.max(image_tensor)
mean_value = np.mean(image_tensor)

print("\n--- Мін/Макс Значення Image Tensor ---")
print("Мінімальне значення:", min_value)
print("Максимальне значення:", max_value)
print("Середнє значення:", mean_value)


--- Мін/Макс Значення Image Tensor ---
Мінімальне значення: 0.0014118523
Максимальне значення: 254.99797
Середнє значення: 127.5486


In [12]:
# 1.8. Створити тензор і стиснути його (squeeze)
# image_tensor вже має форму [1, 224, 224, 3]

squeezed_tensor = np.squeeze(image_tensor)

print("\n--- Стиснення Тензора (Squeeze) ---")
print("Початкова форма:", image_tensor.shape)
print("Стиснута форма:", squeezed_tensor.shape)


--- Стиснення Тензора (Squeeze) ---
Початкова форма: (1, 224, 224, 3)
Стиснута форма: (224, 224, 3)


In [13]:
# 1.9. Створити тензор форми [10] та знайти індекс максимального значення
custom_tensor = np.array([0.1, 0.9, 0.05, 0.5, 0.2, 0.99, 0.3, 0.7, 0.4, 0.8], dtype=np.float32)

max_index = np.argmax(custom_tensor)

print("\n--- Індекс Максимального Значення ---")
print("Тензор:", custom_tensor)
print("Індекс максимального значення (argmax):", max_index)
print("Максимальне значення:", custom_tensor[max_index])


--- Індекс Максимального Значення ---
Тензор: [0.1  0.9  0.05 0.5  0.2  0.99 0.3  0.7  0.4  0.8 ]
Індекс максимального значення (argmax): 5
Максимальне значення: 0.99


In [14]:
# 1.10. One-Hot Кодування
depth = custom_tensor.shape[0] # Кількість класів = 10
# Перетворимо індекс максимального значення (5) на one-hot вектор
one_hot_encoded = np.zeros(depth, dtype=np.float32)
one_hot_encoded[max_index] = 1

print("\n--- One-Hot Кодування ---")
print(f"Індекс для кодування: {max_index}")
print("One-Hot Вектор (максимальний індекс):", one_hot_encoded)


--- One-Hot Кодування ---
Індекс для кодування: 5
One-Hot Вектор (максимальний індекс): [0. 0. 0. 0. 0. 1. 0. 0. 0. 0.]


In [15]:
# 2. Перевірити доступ до графічного процесора
print("\n--- Перевірка Доступу до GPU ---")

try:
    import tensorflow as tf
    gpu_available = tf.config.list_physical_devices('GPU')
    if gpu_available:
        print(f" Доступний GPU: {gpu_available}")
        print("Використання GPU для обчислень буде автоматичним або може бути задано явно.")
    else:
        print(" GPU не знайдено (через TensorFlow).")
except Exception as e:
    print("⚠️ TensorFlow не доступний або виникла помилка при імпорті:", e)
    # Fallback: перевіримо наявність nvidia-smi (NVIDIA GPU)
    import shutil, subprocess
    if shutil.which("nvidia-smi"):
        try:
            out = subprocess.run(["nvidia-smi", "-L"], capture_output=True, text=True, check=True)
            print(" NVIDIA GPU виявлено через nvidia-smi:")
            print(out.stdout.strip())
        except Exception as e2:
            print("NVIDIA інструмент знайдено, але не вдалося виконати nvidia-smi:", e2)
    else:
        print("NVIDIA GPU не знайдено (немає nvidia-smi). Пробуйте встановити драйвери CUDA / NVIDIA або встановити TensorFlow, сумісний з вашим Python.")


--- Перевірка Доступу до GPU ---
⚠️ TensorFlow не доступний або виникла помилка при імпорті: Traceback (most recent call last):
  File "c:\Users\anast\AppData\Local\Programs\Python\Python313\Lib\site-packages\tensorflow\python\pywrap_tensorflow.py", line 73, in <module>
    from tensorflow.python._pywrap_tensorflow_internal import *
ImportError: DLL load failed while importing _pywrap_tensorflow_internal: A dynamic link library (DLL) initialization routine failed.


Failed to load the native TensorFlow runtime.
See https://www.tensorflow.org/install/errors for some common causes and solutions.
If you need help, create an issue at https://github.com/tensorflow/tensorflow/issues and include the entire stack trace above this error message.
NVIDIA GPU не знайдено (немає nvidia-smi). Пробуйте встановити драйвери CUDA / NVIDIA або встановити TensorFlow, сумісний з вашим Python.
⚠️ TensorFlow не доступний або виникла помилка при імпорті: Traceback (most recent call last):
  File "c:\Users\an